
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author darka
 */
public class FrmPong extends javax.swing.JFrame {

    int x2, y2;
    JButton Raqueta;
    JButton Raqueta0;
    Pelota mPelota;

    /**
     * Creates new form FrmPong
     */
    public FrmPong() {
        initComponents();
        setTitle("MCAJ_PONG");
        LblX.setVisible(false);
        LblY.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Raqueta1 = new javax.swing.JButton();
        Raqueta2 = new javax.swing.JButton();
        LblX = new javax.swing.JLabel();
        LblY = new javax.swing.JLabel();
        BtnStart = new javax.swing.JButton();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        Raqueta1.setFocusPainted(false);
        Raqueta1.setFocusable(false);
        Raqueta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Raqueta1ActionPerformed(evt);
            }
        });
        Raqueta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Raqueta1KeyPressed(evt);
            }
        });

        Raqueta2.setFocusPainted(false);
        Raqueta2.setFocusable(false);
        Raqueta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Raqueta2ActionPerformed(evt);
            }
        });

        LblX.setText("jLabel1");

        LblY.setText("jLabel2");

        BtnStart.setFocusPainted(false);
        BtnStart.setFocusable(false);
        BtnStart.setPreferredSize(new java.awt.Dimension(32, 3));
        BtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartActionPerformed(evt);
            }
        });

        score1.setText("Jugador1: 0");

        score2.setText("Jugador2: 0");

        jLabel1.setText("PRECIONA ENTER PARA JUGAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(score1)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(score2)
                .addGap(22, 22, 22))
            .addComponent(BtnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblX)
                    .addComponent(LblY))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Raqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Raqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Raqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Raqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(BtnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(score1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Raqueta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Raqueta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Raqueta1ActionPerformed

    private void Raqueta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Raqueta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Raqueta2ActionPerformed

    private void Raqueta1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Raqueta1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_Raqueta1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int x, y;
        // int x2, y2;
        x = Raqueta1.getX();
        y = Raqueta1.getY();
        x2 = Raqueta2.getX();
        y2 = Raqueta2.getY();
        if (evt.getKeyCode() == VK_S) {
            if ((y <= 150) && (y2 <= 200)) {
                y = y + 10;
                Raqueta1.setLocation(x, y);

            }
        } else if (evt.getKeyCode() == VK_W) {
            if (y > 0) {
                y = y - 10;
                Raqueta1.setLocation(x, y);

            }
        }

        if (evt.getKeyCode() == VK_DOWN) {
            if (y2 <= 150) {
                y2 = y2 + 10;
                Raqueta2.setLocation(x2, y2);

            }
        } else if (evt.getKeyCode() == VK_UP) {
            if (y2 > 0) {
                y2 = y2 - 10;
                Raqueta2.setLocation(x2, y2);

            }
        } else if (evt.getKeyCode() == VK_ENTER) {
            /*Pelota*/ mPelota = new Pelota(x + 160, y + 30, this, Raqueta1, Raqueta2, score1, score2);
            mPelota.start();

        }


    }//GEN-LAST:event_formKeyPressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        LblX.setText("X: " + evt.getX());
       LblY.setText("Y: " + evt.getY());


    }//GEN-LAST:event_formMouseMoved

    private void BtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartActionPerformed
        // TODO add your handling code here:
        
            


    }//GEN-LAST:event_BtnStartActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStart;
    private javax.swing.JLabel LblX;
    private javax.swing.JLabel LblY;
    private javax.swing.JButton Raqueta1;
    private javax.swing.JButton Raqueta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    // End of variables declaration//GEN-END:variables
}
